### PR TITLE
Add rubocop

### PR DESCRIPTION
**Pull request by just1602**
I have taken the [command_kit `.rubocop.yml`](https://github.com/postmodern/command_kit.rb/blob/main/.rubocop.yml), but there are new cops that have been added over the time, and I was not sure what you would prefer, so here's the set of new violation we can fix or disable.

When you have a second, let me know what you prefer, and I'll adjust `.rubocop.yml ` and create a real PR. I can also generate a config with `--auto-gen-config` and open separate PR for each fixes, tho.

* `Gemfile:19:3: C: [Correctable] Bundler/OrderedGems: Gems should be sorted in an alphabetical order within their section of the Gemfile.`
* `Rakefile:8:8: W: [Correctable] Lint/AmbiguousOperator: Ambiguous negative number operator. Parenthesize the method arguments if it's surely a negative number operator, or add a whitespace to the right of the - if it should be a subtraction.`
* `lib/ronin/web/server/base.rb:26:1: W: [Correctable] Lint/RedundantRequireStatement: Remove unnecessary require statement.
require 'thread'`
* `lib/ronin/web/server/base.rb:171:30: W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable - handler. runner = lambda { |handler,server|`
* `lib/ronin/web/server/base.rb:171:30: W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable - handler. runner = lambda { |handler,server|`
* `lib/ronin/web/server/base.rb:173:62: W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable - server. handler.run(server,Host: bind, Port: port) do |server|`
* `lib/ronin/web/server/base.rb:173:62: W: Lint/ShadowingOuterLocalVariable: Shadowing outer local variable -  handler.run(server,Host: bind, Port: port) do |server|`
* `lib/ronin/web/server/base.rb:179:41: W: Lint/UselessAssignment: Useless assignment to variable - e. rescue Errno::EADDRINUSE => e`
* `lib/ronin/web/server/base.rb:180:15: C: [Correctable] Style/StderrPuts: Use warn instead of $stderr.puts to allow such output to be disabled.`                                     
* `lib/ronin/web/server/conditions.rb:68:33: C: Style/CaseEquality: Avoid the use of the case equality operator ===.`
* `lib/ronin/web/server/conditions.rb:383:21: W: Lint/UselessAssignment: Useless assignment to variable - os.` <= this one seems to be an error
* `lib/ronin/web/server/request.rb:62:13: C: [Correctable] Style/Next: Use next to skip iteration.`
* `lib/ronin/web/server/reverse_proxy.rb:153:76: C: [Correctable] Style/HashSyntax: Omit the hash value.`
* `lib/ronin/web/server/reverse_proxy/request.rb:96:13: W: Lint/ReturnInVoidContext: Do not return a value in ssl=.`
* `lib/ronin/web/server/routing.rb:67:38: C: [Correctable] Naming/BlockForwarding: Use anonymous block forwarding.`
* `ronin-web-server.gemspec:1:1: C: [Correctable] Style/Encoding: Unnecessary utf-8 encoding comment.`
* `ronin-web-server.gemspec:35:3: C: [Correctable] Gemspec/DeprecatedAttributeAssignment: Do not set test_files in gemspec.`
* `spec/request_spec.rb:33:44: C: [Correctable] Style/RedundantInterpolation: Prefer to_s over string interpolation.`

### CODE REVIEW

**Comment by postmodern** [comment]
* `Bundler/OrderedGems`: this can be disabled. Gems are grouped together into clusters in the `Gemfile`.
* `Lint/AmbiguousOperator`: this is debatable. I guess I could see `foo -1` and `foo - 1` being confused, but `exit -1` is pretty common.
* `lib/ronin/web/server/base.rb:26:1: W: [Correctable] Lint/RedundantRequireStatement: Remove unnecessary require statement. require 'thread'`: Fixed in 83699b7db30cbc317a3f2ab9553dcc6c42f6889e.
* `lib/ronin/web/server/base.rb:171 - 180`: This code was copied from [Sinatra::Base#run!](https://github.com/sinatra/sinatra/blob/815b69fe2510930de97a89f9318fcfa35165e96e/lib/sinatra/base.rb#L1500-L1517) but allows running it in the background in a Thread, and overrides the error message if the port is already in-use. Not sure what the best way to rewrite the code?
* `Style/CaseEquality`: this can be disabled for `lib/ronin/web/server/conditions.rb`. I explicitly use `===` to allow matching both the exact String via `String#====` or a regexp match via `Regexp#====`.
* `Style/Next`: this is debatable. I generally prefer to allow the enumerator to enumerate and wrap everything in an `if`/`unless`. If there's a performance advantage to using `next if ...` then I'll accept changing that code.
* `lib/ronin/web/server/reverse_proxy.rb:153:76: C: [Correctable] Style/HashSyntax:`: This appears to be incorrect. `Hash#fetch` does not set the key's value by default, just returns the value. In this method we need to persist the newly opened connection.
* `Lint/ReturnInVoidContext`: this can be disabled. Due to years of writing C/C++ I often use `return`, often unnecessarily, in Ruby.
* `Naming/BlockForwarding`: this seems counter-intuitive. You'd think rubocop would prefer explicit `&block` passing over implicit block passing. Also, implicit block passing has bitten me more than a few times.
* `ronin-web-server.gemspec:1:1: C: [Correctable] Style/Encoding: Unnecessary utf-8 encoding comment.`: I'll take it. e14e30a64fd5ef8f55cdc9fc05407cd7ef6c5f08
* `ronin-web-server.gemspec:35:3: C: [Correctable] Gemspec/DeprecatedAttributeAssignment`: so `gemspec.test_files` isn't actually deprecated just yet, but rubocop decided to flag it anyways. I should probably explicitly filter out any `spec/` files in order to prevent possibly triggering any security scanners; I've already done this in `ronin-support`'s gemspec file since the specs contain dummy CC numbers.
* `spec/request_spec.rb:33:44: C: [Correctable] Style/RedundantInterpolation`: I'll take it. bd8c328791a6fd15f1349cfcfabbed89bb815820

**Comment by just1602** [comment]
I'm wondering if I should remove all the autogenerated stuff from the `command_kit` config, but if I do so, it'll generate a lot of errors for double quote string without interpolation and stuff like that. Is this something you want?

**Comment by postmodern** [comment]
@just1602 it's probably safer to keep the `command_kit` rubocop config. My coding style in `command_kit` won't be different from my coding style in ronin.

**Comment by postmodern** [comment]
Also added rubocop to the GitHub Actions workflow in 644930d6fa524f7e2dc1d28efaea33765153d367.

**Comment by just1602** [comment]
I'd have added the GitHub action in another PR, but nice if it's done. I'll try to reproduce in other module.

**Pull request merged**
